config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tops#index'
  resources :tops, only: :index
  resources :stocks, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :memos, only: [:index, :new, :create, :edit, :update, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
  validates :title, presence: true

  belongs_to :user
end

app/models/stock.rb
class Stock < ApplicationRecord
  validates :food_name, presence: true
  validates :expiration_date, presence: true
  validates :image, presence: true

  belongs_to :user
  has_many :stock_tags, dependent: :destroy
  has_many :tags, through: :stock_tags
  has_one_attached :image

  def self.search_for_user(user, search)
    if search.present?
      user.stocks.where('food_name LIKE ?', "%#{search}%")
    else
      user.stocks
    end
  end

  scope :expiring_in_one_month, -> {
    where("expiration_date = ?", 1.month.from_now.to_date)
  }
  scope :expiring_in_one_week, -> {
    where("expiration_date = ?", 1.week.from_now.to_date)
  }
  scope :today, -> { where(expiration_date: Date.today) }
end

app/models/stock_form.rb
class StockForm
  include ActiveModel::Model

  attr_accessor(
    :food_name, :expiration_date, :memo, :image,
    :id, :created_at, :updated_at,
    :tag_name, :user_id
  )
  
  with_options presence: true do
    validates :food_name
    validates :expiration_date
  end

  validates :image, presence: { message: "を選択してください" }

  def save(tag_list)
    stock = Stock.create(food_name: food_name, expiration_date: expiration_date, memo: memo, image: image, user_id: user_id)
    
    # 複数のタグを保存
    tag_list.each do |tag_name|
      tag = Tag.where(tag_name: tag_name).first_or_initialize
      tag.save

      StockTag.create(stock_id: stock.id, tag_id: tag.id)
    end
  end

  def update(params, stock, tag_list)
    #一度タグの紐付けを消す
    stock.stock_tags.destroy_all

    #paramsの中のタグの情報を削除。同時に、返り値としてタグの情報を変数に代入
    tag_name = params.delete(:tag_name)

    #もしタグの情報がすでに保存されていればインスタンスを取得、無ければインスタンスを新規作成
    tag_list.each do |tag_name|
      tag = Tag.where(tag_name: tag_name).first_or_initialize
      # タグを保存
      tag.save
      StockTag.create(stock_id: stock.id, tag_id: tag.id)
    end
    stock.update(params)
  end
end

app/models/stock_tag.rb
class StockTag < ApplicationRecord
  belongs_to :stock
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :tag_name, uniqueness: true

  has_many :stock_tags, dependent: :destroy
  has_many :stocks, through: :stock_tags

  def self.search_for_user(user, search)
    if search.present? && search != '#'
      tag = Tag.where(tag_name: search).first
      tag.stocks.where(user_id: user.id)
    else
      user.stocks
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  
  has_many :stocks
  has_many :memos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?


  private
  # Basic認証の設定
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"] 
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_memo, only: [:edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :destroy]


  def index
    # ログインユーザーの投稿のみの表示
    @user_memos = current_user.memos.order("created_at DESC")
  end

  def new
    @memo = Memo.new
  end

  def create
    @memo = Memo.create(memo_params)
    if @memo.save
      redirect_to memos_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @memo.update(memo_params)
      redirect_to memos_path
    else
      render :edit
    end
  end

  def destroy
    @memo.destroy
    redirect_to memos_path
  end

  private
  def memo_params
    params.require(:memo).permit(:title, :memo).merge(user_id: current_user.id)
  end

  def set_memo
    @memo = Memo.find(params[:id])
  end

  def move_to_index
    unless user_signed_in? && current_user.id == @memo.user_id
      redirect_to action: :index
    end
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_stock, only: [:edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :destroy]
  
  def index
    # ログインユーザーの投稿のみの表示
    @user_stocks = current_user.stocks.order("expiration_date ASC")

    # 賞味期限までの残日数の表示
    @remaining_days = {}
    @user_stocks.each do |stock|
      if stock.expiration_date.present?
        remaining_days = (stock.expiration_date - Date.today).to_i
        @remaining_days[stock.id] = remaining_days
      end
    end
  end

  def new
    @stock_form = StockForm.new
  end

  def create
    @stock_form = StockForm.new(stock_form_params)

    # 複数のタグを,で区切って配列に保存
    tag_list = prepare_tags(params[:stock_form][:tag_name])
    
    if @stock_form.valid?
      @stock_form.save(tag_list)
      redirect_to stocks_path
    else
      render :new
    end
  end

  def edit
    stock_attributes = @stock.attributes
    @stock_form = StockForm.new(stock_attributes)

    #複数タグの表示
    @stock_form.tag_name = @stock.tags.pluck(:tag_name).join(',')
  end

  def update
    @stock_form = StockForm.new(stock_form_params)

    # 画像を選択し直していない場合は、既存の画像をセットする
    @stock_form.image ||= @stock.image.blob

    # タグの複数保存
    tag_list = prepare_tags(params[:stock_form][:tag_name])

    if @stock_form.valid?
      @stock_form.update(stock_form_params, @stock, tag_list)
      redirect_to stocks_path
    else
      render :edit
    end
  end

  def destroy
    if @stock.destroy
      redirect_to stocks_path
    end
  end

  def search
    @user_stocks = current_user.stocks

    if (params[:keyword])[0] == '#'
      @user_stocks = Tag.search_for_user(current_user, params[:keyword]).order("expiration_date ASC")
    else
      @user_stocks = Stock.search_for_user(current_user, params[:keyword]).order("expiration_date ASC")
    end

    # 賞味期限までの残日数の表示
    @remaining_days = {}
    @user_stocks.each do |stock|
      if stock.expiration_date.present?
        remaining_days = (stock.expiration_date - Date.today).to_i
        @remaining_days[stock.id] = remaining_days
      end
    end
  end

  private
  def stock_form_params
    params.require(:stock_form).permit(:food_name, :expiration_date, :memo, :tag_name, :image).merge(user_id: current_user.id)
  end

  def prepare_tags(tags_string)
    tags = tags_string.split(",")
    formatted_tags = tags.map do |tag|
      tag.strip.start_with?("#") ? tag.strip : "##{tag.strip}"
    end
  end

  def set_stock
    @stock = Stock.find(params[:id])
  end

  def move_to_index
    unless user_signed_in? && current_user.id == @stock.user_id
      redirect_to action: :index
    end
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
 <div class="error-alert">
   <ul>
     <% model.errors.full_messages.each do |message| %>
       <li class='error-message'><%= message %></li>
     <% end %>
   </ul>
 </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
       <nav class="navbar navbar-expand-md bg-body-secondary" data-bs-theme="dark">
        <div class="container-fluid">
          <%= link_to 'StockList', root_path, class:"navbar-brand" %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <%# ログインしている時の表示 %>
          
            <div class="collapse navbar-collapse" id="navbar">
              <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to '在庫一覧', stocks_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to '買い物リスト', memos_path, class:"nav-link" %>
                </li>
              </ul>

              <ul class="navbar-nav justify-content-end">
                <li class="nav-item">
                  <a class="nav-link disabled text-white"><%= current_user.name %>さん</a>
                </li>
                <li class="nav-item">
                  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"nav-link" %>
                </li>

                <% else %>
              
              <%# ログインしていない時の表示 %>
                <li class="nav-item">
                  <%= link_to 'ログイン', new_user_session_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to '新規登録', new_user_registration_path, class:"nav-link" %>
                </li>
                <% end %>
              </ul>
            </div>
        </div>
      </nav>
    </header>
    
    <%= yield %>
    
  </body>
</html>

app/views/memos/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6" style="width:500px;">
      <%= form_with model: @memo, url: url, method: method, id: 'new_memo', local: true do |f| %>
      
      <%# エラーメッセージ表示 %>
      <%= render 'shared/error_messages', model: f.object %>

        <div class="message-field mb-2">
          <%= f.label :name, "商品名", class:"form-label"%><br />
          <%= f.text_field :title, class:"form-control" %>
        </div>
        <div class="tag_field mb-2">
          <%= f.label :name, "備考欄", class:"form-label"  %><br />
          <%= f.text_field :memo, class:"form-control" %>
        </div>
        <div class="submit-btn mb-2 text-center">
          <%= f.submit '送信', class:"btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/memos/edit.html.erb
<div class="cintainer">
  <div class="row">
    <div class="col-12 col-md-6 mx-auto mt-3" >
      <h3 class="m-3 fw-bold">買い物リストの編集ページ</h3>
      <%= render partial: "form", locals: {url: memo_path(@memo.id), method: :patch} %>
    </div>
  </div>
</div>

app/views/memos/index.html.erb
<nav class="navbar navbar-expand-md bg-body-secondary" data-bs-theme="light">
  
</nav>

<div class="container">
  <div class="row m-4">
    <div class="col-12 col-md-6 mb-3">
      <h1 class="mr-1 fw-bold">買い物リスト</h5>
    </div>
    <div class="d-grid gap-2 d-md-block">
      <%= link_to '新規登録', new_memo_path, class:"btn btn-primary mb-3" %>
    </div>
    <%# 買い物リスト %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">商品名</th>
          <th scope="col">備考欄</th>
          <th scope="col">登録日</th>
          <th colspan="1"></th>
        </tr>
      </thead>
      <tbody>
        <% @user_memos.each do |memo| %>
        <tr>
          <td><%= memo.title %></td>
          <td><%= memo.memo %></td>
          <td><%= memo.created_at.strftime('%Y-%m-%d %H:%M') %></td>
          <td>
            <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
              <%= link_to '編集', edit_memo_path(memo.id), class:"btn btn-outline-secondary"%>
              <%= link_to '削除', memo_path(memo.id), method: :delete, class:"btn btn-outline-secondary"%>
              <!-- <button type="button" class="btn btn-outline-secondary">編集</button>
              <button type="button" class="btn btn-outline-secondary">削除</button> -->
            </div>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/memos/new.html.erb
<div class="cintainer">
  <div class="row">
    <div class="col-12 col-md-6 mx-auto mt-3" >
      <h3 class="m-3 fw-bold">買い物リストの新規登録ページ</h3>
      <%= render partial: "form", locals: {url: memos_path, method: :post} %>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul class="mb-0">
    <% model.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/stocks/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6" style="width:500px;">
      <%= form_with model: @stock_form, url: url, method: method, id: 'new_stock', local: true do |f| %>
      
      <%# エラーメッセージ表示 %>
      <%= render 'shared/error_messages', model: f.object %>

        <div class="message-field mb-2">
          <%= f.label :name, "商品名", class:"form-label"%><br />
          <%= f.text_field :food_name, class:"form-control" %>
        </div>
        <div class="tag_field mb-2">
          <%= f.label :name, "賞味期限", class:"form-label" %><br />
          <%= f.date_field :expiration_date, class:"form-control" %>
        </div>
        <div class="tag_field mb-2">
          <%= f.label :name, "備考欄", class:"form-label"  %><br />
          <%= f.text_area :memo, class:"form-control" %>
        </div>
        <div class="tag_field mb-3">
          <%= f.label :name, "タグ", class:"form-label"  %><br />
          <%= f.text_field :tag_name, class:"form-control" %>
          <div class="form-text">最初に「＃」を入れてください。「,」で区切ると複数タグ登録できます</div>
        </div>
        <div class="image-field mb-3">
          <div class="click-upload">
            <%= f.file_field :image %>
          </div>
        </div>
        <div class="submit-btn mb-2 text-center">
          <%= f.submit '送信', class:"btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/stocks/_header.html.erb
<nav class="navbar navbar-expand-md bg-body-secondary" data-bs-theme="light">
  <div class="container-fluid">
    <%= link_to '在庫登録', new_stock_path, class:"btn btn-primary" %>
    <div class="collapse navbar-collapse justify-content-lg-end" id="navbar">
      <%= form_with(url: search_stocks_path, local: true, method: :get, class: "d-flex") do |form| %>
        <%= form.text_field :keyword, placeholder: "在庫一覧から検索", class: "form-control me-2" %>
        <%= form.submit "検索", class: "btn btn-outline-primary" %>
      <% end %>
    </div>
  </div>
</nav>

<!-- 商品名 or #タグ名の検索 -->

app/views/stocks/_index.html.erb
<%# 在庫一覧の表示 %>
<div class="album py-5">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <% @user_stocks.each do |stock| %>
      <div class="col-md-4 mb-4">
        <div class="card shadow-sm h-100">
          <%= image_tag stock.image, class: "card-img-top img-fluid" %>
          <div class="card-body">
            <h5 class="card-title fw-bold"><%= stock.food_name %></h5>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">備考欄：<%= stock.memo %></li>
              <li class="list-group-item">タグ：
                <% stock.tags.each do |tag| %>
                  <%= tag.tag_name %>
                  <%# "##{tag.tag_name}" %>
                <% end %>
              </li>
              <li class="list-group-item fw-bold">賞味期限：<%= stock.expiration_date %></li>
            </ul>
            <div class="d-flex justify-content-between align-items-center mt-3">
              <div class="btn-group">
                <%= link_to '編集', edit_stock_path(stock.id), class:"btn btn-sm btn-outline-secondary"%>
                <%= link_to '削除', stock_path(stock.id), method: :delete, class:"btn btn-sm btn-outline-secondary"%>
              </div>
              <% if stock.expiration_date.present? %>
                <% remaining_days = @remaining_days[stock.id] %>
                <% if remaining_days >= 0 %>
                  <% if remaining_days <= 7 %>
                    <%# 残り7日以下の表示 %>
                    <h5 style="color: red;" class="fw-bold">残り <%= remaining_days %> 日</h5>
                  <% else %>
                    <h5>残り <%= remaining_days %>日</h5>
                  <% end %>
                <% else %>
                  <%#  期日を過ぎているときの表示%>
                  <h5 style="color: red;" class="fw-bold">過ぎています</h5>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/stocks/edit.html.erb
<div class="cintainer">
  <div class="row">
    <div class="col-12 col-md-6 mx-auto mt-3" >
      <h3 class="m-3 fw-bold">非常食の編集ページ</h3>
      <%= render partial: "form", locals: {url: stock_path(@stock.id), method: :patch} %>
    </div>
  </div>
</div>

app/views/stocks/index.html.erb
<%= render partial: "header" %>

<%= render partial: "index" %>

app/views/stocks/new.html.erb
<div class="cintainer">
  <div class="row">
    <div class="col-12 col-md-6 mx-auto mt-3" >
      <h3 class="m-3 fw-bold">非常食の新規登録ページ</h3>
      <%= render partial: "form", locals: {url: stocks_path, method: :post} %>
    </div>
  </div>
</div>

app/views/stocks/search.html.erb
<%= render partial: "header" %>

<%= render partial: "index" %>

app/views/tops/index.html.erb
<div class="cotainer">
  <div class="row">
    <div class="col-12 col-md-6 text-center mx-auto mt-5">
      <div class="mb-5">
        <%= image_tag "can.png", size: "200x200", class:"mb-3" %>
        <h1 class="mb-3 fw-bold">StockListとは</h1>
        <p class="mb-5">非常食の賞味期限を管理できるアプリです。<br>
          非常食は物によって賞味期限が長いものが多く、<br>
          気づかないうちに期限が切れてることもしばしば。<br>
          いつ起こるかわからない災害。<br>
          いざという時に困らないように開発したアプリです</p>
      </div>
      <div class="px-4 py-5 mb-5">
        <%= image_tag "bag.png", size: "200x200", class:"mb-3" %>
        <h1 class="mb-3 fw-bold">主な機能</h1>
        <p class="mb-2">1.在庫一覧で非常食の賞味期限を登録すれば、<br>
          残り何日かのカウントをします。</p>
        <p class="mb-2">2.賞味期限が切れる１ヶ月前、１週間前、当日に<br>
          メールでお知らせします。</p>
        <p class="mb-2">3.ローリングストックできるよう、<br>
          消費後は買い物リストに追加しましょう。</p>
      </div>
      <div>
        <%= image_tag "water.png", size: "200x200", class:"mb-3" %>
        <h1 class="mb-3 fw-bold">賞味期限？消費期限？</h1>
        <h4 class="mb-2 fw-bold">賞味期限とは</h4>
        <p class="mb-5">未開封の状態であれば、<br>
          <strong>品質が変わらず美味しく食べられる期間</strong>のことです。<br>
          この期限が過ぎたからといって、<br>
          すぐ食べられなくなるというわけではありません。<br>
          主に傷みにくい食品に表示されています。</p>
        <h4 class="mb-2 fw-bold">消費期限とは</h4>
        <p class="mb-5">未開封の状態であれば、<br>
          <strong>安全に食べることができる期間</strong>のことです。<br>
          賞味期限とは違い、傷みやすい食品に表示されています。</p>
      </div>
    </div>
  </div>
</div>